export const KLOES = ['Safe', 'Effective', 'Caring', 'Responsive', 'Well-led'] as const
export const RISK_LEVELS = ['Low', 'Medium', 'High'] as const
export const RESIDENT_STATUSES = ['Active', 'Hospital', 'Respite'] as const
export const EMPLOYMENT_TYPES = ['Permanent', 'Bank', 'Agency'] as const
export const STAFF_STATUSES = ['Compliant', 'Due soon', 'Action required'] as const
export const AUDIT_STATUSES = ['Scheduled', 'In progress', 'Complete'] as const
export const COMPLIANCE_STATUSES = ['Compliant', 'In progress', 'Action required', 'Overdue'] as const
export const INCIDENT_TYPES = ['Fall', 'Medication', 'Safeguarding', 'Behaviour', 'Skin integrity', 'Other'] as const
export const SEVERITIES = ['Low', 'Medium', 'High', 'Critical'] as const
export const INCIDENT_STATUSES = ['Open', 'Investigating', 'Closed'] as const
export const ASSET_CATEGORIES = ['Medical', 'Safety', 'Mobility', 'Furniture'] as const
export const ASSET_CONDITIONS = ['Excellent', 'Good', 'Fair', 'Poor'] as const
export const ASSET_STATUSES = ['Operational', 'Service due', 'Out of service'] as const
export const NOTIFICATION_TYPES = ['Alert', 'Warning', 'Update'] as const
export const NOTIFICATION_PRIORITIES = ['High', 'Medium', 'Low'] as const
export const SHIFT_TYPES = ['Early', 'Late', 'Night', 'Long day'] as const
export const MEDICATION_ROUTES = ['Oral', 'Topical', 'Inhaled', 'Injection'] as const
export const MEDICATION_STATUSES = ['Active', 'Paused', 'Discontinued'] as const
export const TRAINING_CATEGORIES = ['Mandatory', 'Core', 'Specialist'] as const
export const TRAINING_FREQUENCIES = ['Annual', 'Two-yearly', 'Three-yearly', 'One-off'] as const
export const TRAINING_STATUSES = ['Current', 'Due soon', 'Overdue'] as const
export const MAINTENANCE_CATEGORIES = ['Statutory', 'PPM', 'Reactive', 'Inspection'] as const
export const MAINTENANCE_PRIORITIES = ['Low', 'Medium', 'High'] as const
export const MAINTENANCE_STATUSES = ['Scheduled', 'In progress', 'Complete', 'Overdue'] as const
export const RISK_CATEGORIES = ['Clinical', 'Environmental', 'Workforce', 'Safeguarding', 'Fire'] as const
export const RISK_LIKELIHOODS = ['Low', 'Medium', 'High'] as const
export const OPERATIONAL_RISK_LEVELS = ['Low', 'Medium', 'High', 'Critical'] as const
export const RISK_STATUSES = ['Open', 'Mitigating', 'Accepted', 'Closed'] as const
export const DOCUMENT_CATEGORIES = ['Policy', 'Certificate', 'Evidence', 'Inspection', 'Training'] as const
export const DOCUMENT_STATUSES = ['Current', 'Review due', 'Expired'] as const
export const ENQUIRY_STAGES = ['New', 'Assessment', 'Viewing', 'Waiting list', 'Offered', 'Admitted'] as const
export const ENQUIRY_SOURCES = ['Family', 'Hospital', 'Local authority', 'GP', 'Website', 'Other'] as const
export const ENQUIRY_CARE_TYPES = ['Residential', 'Nursing', 'Dementia', 'Respite'] as const
export const ENQUIRY_URGENCIES = ['Immediate', 'Within a week', 'Within a month', 'Future'] as const

export type Kloe = (typeof KLOES)[number]
export type RiskLevel = (typeof RISK_LEVELS)[number]
export type ResidentStatus = (typeof RESIDENT_STATUSES)[number]
export type EmploymentType = (typeof EMPLOYMENT_TYPES)[number]
export type StaffStatus = (typeof STAFF_STATUSES)[number]
export type AuditStatus = (typeof AUDIT_STATUSES)[number]
export type RecordStatus = (typeof COMPLIANCE_STATUSES)[number]
export type IncidentType = (typeof INCIDENT_TYPES)[number]
export type Severity = (typeof SEVERITIES)[number]
export type IncidentStatus = (typeof INCIDENT_STATUSES)[number]
export type AssetCategory = (typeof ASSET_CATEGORIES)[number]
export type AssetCondition = (typeof ASSET_CONDITIONS)[number]
export type AssetStatus = (typeof ASSET_STATUSES)[number]
export type NotificationType = (typeof NOTIFICATION_TYPES)[number]
export type NotificationPriority = (typeof NOTIFICATION_PRIORITIES)[number]
export type ShiftType = (typeof SHIFT_TYPES)[number]
export type MedicationRoute = (typeof MEDICATION_ROUTES)[number]
export type MedicationStatus = (typeof MEDICATION_STATUSES)[number]
export type TrainingCategory = (typeof TRAINING_CATEGORIES)[number]
export type TrainingFrequency = (typeof TRAINING_FREQUENCIES)[number]
export type TrainingStatus = (typeof TRAINING_STATUSES)[number]
export type MaintenanceCategory = (typeof MAINTENANCE_CATEGORIES)[number]
export type MaintenancePriority = (typeof MAINTENANCE_PRIORITIES)[number]
export type MaintenanceStatus = (typeof MAINTENANCE_STATUSES)[number]
export type RiskCategory = (typeof RISK_CATEGORIES)[number]
export type RiskLikelihood = (typeof RISK_LIKELIHOODS)[number]
export type OperationalRiskLevel = (typeof OPERATIONAL_RISK_LEVELS)[number]
export type RiskRegisterStatus = (typeof RISK_STATUSES)[number]
export type DocumentCategory = (typeof DOCUMENT_CATEGORIES)[number]
export type DocumentStatus = (typeof DOCUMENT_STATUSES)[number]
export type EnquiryStage = (typeof ENQUIRY_STAGES)[number]
export type EnquirySource = (typeof ENQUIRY_SOURCES)[number]
export type EnquiryCareType = (typeof ENQUIRY_CARE_TYPES)[number]
export type EnquiryUrgency = (typeof ENQUIRY_URGENCIES)[number]

export const kloeFilterOptions = ['All KLOEs', ...KLOES]
export const riskFilterOptions = ['All risk levels', ...RISK_LEVELS]
export const residentStatusFilterOptions = ['All statuses', ...RESIDENT_STATUSES]
export const employmentFilterOptions = ['All employment', ...EMPLOYMENT_TYPES]
export const staffStatusFilterOptions = ['All statuses', ...STAFF_STATUSES]
export const auditStatusFilterOptions = ['All statuses', ...AUDIT_STATUSES]
export const complianceStatusFilterOptions = ['All statuses', ...COMPLIANCE_STATUSES]
export const severityFilterOptions = ['All severities', ...SEVERITIES]
export const assetCategoryFilterOptions = ['All categories', ...ASSET_CATEGORIES]
export const assetStatusFilterOptions = ['All statuses', ...ASSET_STATUSES]
export const incidentStatusTabs = ['All', ...INCIDENT_STATUSES] as const
export const notificationFilters = ['All', 'Unread', 'Alerts', 'Warnings'] as const
export const shiftTypeFilterOptions = ['All shift types', ...SHIFT_TYPES]
export const medicationStatusFilterOptions = ['All statuses', ...MEDICATION_STATUSES]
export const trainingStatusFilterOptions = ['All statuses', ...TRAINING_STATUSES]
export const maintenanceStatusFilterOptions = ['All statuses', ...MAINTENANCE_STATUSES]
export const riskStatusFilterOptions = ['All statuses', ...RISK_STATUSES]
export const documentCategoryFilterOptions = ['All categories', ...DOCUMENT_CATEGORIES]
export const enquiryStageFilterOptions = ['All stages', ...ENQUIRY_STAGES]
export const enquirySourceFilterOptions = ['All sources', ...ENQUIRY_SOURCES]
