---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/njtest.koptechnology.co.uk
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/bash -lc 'if [ "$(pwd -P)" != "$(cd "$HOME/njtest.koptechnology.co.uk" && pwd -P)" ]; then /bin/cp -R .next prisma "$HOME/njtest.koptechnology.co.uk/"; /bin/cp package.json package-lock.json next.config.ts server.js .env.example "$HOME/njtest.koptechnology.co.uk/"; fi'
    - /usr/bin/touch "$HOME/njtest.koptechnology.co.uk/.htaccess"
    - /bin/mkdir -p "$HOME/njtest.koptechnology.co.uk/tmp"
    - /usr/bin/touch "$HOME/njtest.koptechnology.co.uk/tmp/restart.txt"
