#!/bin/sh
# Generated by .github/workflows/verify.yml. Do not edit by hand.
# Recreates the module links `next build` emitted, rooted at the application root.
set -eu
APPROOT="${1:-$(pwd)}"
mkdir -p "$APPROOT/.next/node_modules/@prisma"
ln -sfn "$APPROOT/node_modules/@prisma/client" "$APPROOT/.next/node_modules/@prisma/client-2c3a283f134fdcb6"
